const ReduxState = {
    importedData: {
        dataFields: [],
        dataObjects: [],
        dataArrays: [],
    },
    analysedData: {
        fields: [],
        intervalFields: [],
        intervalDataObjects: [],
        nominalFields: [],
        nominalDataObjects: [],
        ordinalFields: [],
        ordinalDataObjects: [],
        binaryFields: [],
        binaryDataObjects: [],
        ignoreFields: [],
        ignoreDataObjects: [],
    },
    lineSeriesOptions: {},
    currentLineVisual: {},
    barSeriesOptions: {},
    currentBarVisual: {},
    markSeriesOptions: {},
    currentMarkVisual: {},
    heatmapSeriesOptions: {},
    currentHeatmapVisual: {},
    polygonSeriesOptions: {},
    currentPolygonVisual: {},
};
export default ReduxState;
