/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:9aa707c3-c86a-40f3-84fa-09b9bdbab318",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_uThvo2Aqq",
    "aws_user_pools_web_client_id": "2lgcc29a9l2e0aaumpoj69c023",
    "oauth": {}
};


export default awsmobile;
