/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:697f77ef-9485-4c31-b74f-25851bd7a78c",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_MrXfpvcRx",
    "aws_user_pools_web_client_id": "65cu49dsknn1sng1784ih0jqc1",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "DataVisAPI",
            "endpoint": "https://iokinm6v9c.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
